import { Book } from "./types";

export const book: Book[] = [
  {
    book_name: "الفيل الازرق",
    bookURL: "www.example.com",
    id: 1,
    serial: [
      { id: 1, book_serial: "asdafdsfd", isUsed: true },
      { id: 2, book_serial: "asdafsfd", isUsed: false },
      { id: 1, book_serial: "asdafdsfd", isUsed: true },
      { id: 2, book_serial: "asdafsfd", isUsed: false },
      { id: 1, book_serial: "asdafdsfd", isUsed: true },
      { id: 2, book_serial: "asdafsfd", isUsed: false },
      { id: 1, book_serial: "asdafdsfd", isUsed: true },
      { id: 2, book_serial: "asdafsfd", isUsed: false },
      { id: 1, book_serial: "asdafdsfd", isUsed: true },
      { id: 2, book_serial: "asdafsfd", isUsed: false },
      { id: 1, book_serial: "asdafdsfd", isUsed: true },
      { id: 2, book_serial: "asdafsfd", isUsed: false },
      { id: 1, book_serial: "asdafdsfd", isUsed: true },
      { id: 2, book_serial: "asdafsfd", isUsed: false },
      { id: 1, book_serial: "asdafdsfd", isUsed: true },
      { id: 2, book_serial: "asdafsfd", isUsed: false },
      { id: 1, book_serial: "asdafdsfd", isUsed: true },
      { id: 2, book_serial: "asdafsfd", isUsed: false },
      { id: 1, book_serial: "asdafdsfd", isUsed: true },
      { id: 2, book_serial: "asdafsfd", isUsed: false },
      { id: 1, book_serial: "asdafdsfd", isUsed: true },
      { id: 2, book_serial: "asdafsfd", isUsed: false },
      { id: 1, book_serial: "asdafdsfd", isUsed: true },
      { id: 2, book_serial: "asdafsfd", isUsed: false },
      { id: 1, book_serial: "asdafdsfd", isUsed: true },
      { id: 2, book_serial: "asdafsfd", isUsed: false },
      { id: 1, book_serial: "asdafdsfd", isUsed: true },
      { id: 2, book_serial: "asdafsfd", isUsed: false },
      { id: 1, book_serial: "asdafdsfd", isUsed: true },
      { id: 2, book_serial: "asdafsfd", isUsed: false },
      { id: 1, book_serial: "asdafdsfd", isUsed: true },
      { id: 2, book_serial: "asdafsfd", isUsed: false },
      { id: 1, book_serial: "asdafdsfd", isUsed: true },
      { id: 2, book_serial: "asdafsfd", isUsed: false },
      { id: 1, book_serial: "asdafdsfd", isUsed: true },
      { id: 2, book_serial: "asdafsfd", isUsed: false },
      { id: 1, book_serial: "asdafdsfd", isUsed: true },
      { id: 2, book_serial: "asdafsfd", isUsed: false },
      { id: 1, book_serial: "asdafdsfd", isUsed: true },
      { id: 2, book_serial: "asdafsfd", isUsed: false },
      { id: 1, book_serial: "asdafdsfd", isUsed: true },
      { id: 2, book_serial: "asdafsfd", isUsed: false },
      { id: 1, book_serial: "asdafdsfd", isUsed: true },
      { id: 2, book_serial: "asdafsfd", isUsed: false },
      { id: 1, book_serial: "asdafdsfd", isUsed: true },
      { id: 2, book_serial: "asdafsfd", isUsed: false },
      { id: 1, book_serial: "asdafdsfd", isUsed: true },
      { id: 2, book_serial: "asdafsfd", isUsed: false },
    ],
  },
];
